env:
  browser: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  "no-var": "error"
  "prefer-const": "error"
  "no-extra-bind": "error"
  "no-implicit-globals": "error"
  "react/no-unknown-property": ["error", { ignore: ["class"] }]
  "@typescript-eslint/member-delimiter-style": ["error", {
    multiline: {
      delimiter: 'none',
      requireLast: false,
    },
    singleline: {
      delimiter: 'comma',
      requireLast: false,
    },
  }]
  "quotes": ["error", "single", { "avoidEscape": true }]
  "indent": ["error", 2]
  "comma-dangle": ["error", {
    "objects": "always-multiline"
  }]
settings:
  react:
    # If this line cause problem in future. Check https://github.com/yannickcr/eslint-plugin-react/issues/1955
    version: 'latest'
